### ISSUE TITLE
Swap out the Version String for a Version Pill, like in Gnome About Dialogs.

### ISSUE THREAD

**Issue by JanluOfficial** [rhino-linux/rhino-system#18]
About Dialogs in Gnome Applications put their version intormation in a clickable pill, that when clicked copies this information to the clipboard.

Gnome Software (45.rc) for reference
![grafik](https://github.com/rhino-linux/rhino-system/assets/95766563/b8f4e3c7-52fe-42df-b598-b2f744d44bf4)

This pill would be placed where the version information currently is.
![grafik](https://github.com/rhino-linux/rhino-system/assets/95766563/38532b9b-1edd-42e4-8a51-890860db137a)

**Comment by JanluOfficial** [comment]
This will continue on https://github.com/rhino-linux/rhino-system/pull/20

**Comment by ajstrongdev** [comment]
Reopened because it should not have been closed.

**Comment by ajstrongdev** [comment]
Moving to rollover for 2023.4 from "Review"

**Comment by ajstrongdev** [comment]
@JanluOfficial Have the changes that have been requested by @axtloss been made?

**Comment by JanluOfficial** [comment]
> @JanluOfficial Have the changes that have been requested by @axtloss been made?

I implemented in a global way that uses Gdk instead of xclip.
