### ISSUE TITLE
BUG: Installer will not boot after grub select for Intel Nuc 12 Extreme (Serpent Canyon).  Stuck on "EFI stub: Measured initrd data into PCR 9"

### ISSUE THREAD

**Issue by Daxiongmao87** [rhino-linux/rhino-system#21]
**Rhino Linux Version:**
2023.3

**Platform:**
amd64

**Describe the bug**
I used Ventoy to create a bootable usb.  I have disabled secure boot.  I select Rhino Linux within Ventoy boot screen.  It then directs me to the grub boot screen.  I've tried both normal and safemode options for 'try/install Rhino Linux,' as well as OEM install option.  However, the same result occurs  -- a blank screen.

Using the boot parameter nomodeset, I am greeted with `EFI stub: Measured initrd data into PCR 9`, to which the boot stays, and does not progress further.

**To Reproduce**
1. Write ISO to USB using Ventoy
2. Disable Secure Boot
3. Boot into Rhino Linux installer and select grub options, enter nomodeset (to see text output)
4. Stuck on 'Select boot option for usb disk (using vent'

**Expected behavior**
1. Write ISO to USB using Ventoy
2. Disable Secure Boot
3. Boot into Rhino Linux installer and select grub options, enter nomodeset (to see text output)
4. Boot into live version of Rhino Linux

**Screenshots**
N/A

**Additional context**
I have installed the latest BIOS version for my machine.
Here is a link to the NUC I am using: https://www.intel.com/content/www/us/en/products/sku/196170/intel-nuc-12-enthusiast-kit-nuc12snki72/specifications.html

**Comment by Daxiongmao87** [comment]
I am willing to try any suggestions and provide results if necessary.

**Comment by axtloss** [comment]
This issue does not have anything to do with rhino system, please open the issue in the right repository.

**Comment by ajstrongdev** [comment]
@Daxiongmao87 Please open in https://github.com/rhino-linux/os instead.

**Comment by Daxiongmao87** [comment]
thank you will do.
