### ISSUE TITLE
BUG: [Can't start mousepad or gedit]

### ISSUE THREAD

**Issue by paulyang81** [rhino-linux/rhino-system#24]
**Rhino Linux Version:*2024.1  (mainline) x86_64 *
A numerical version for Rhino Linux. Example: `2023.1`, - Version number can be found by running `neofetch` (preinstalled) or with the "Your System" application.

**Platform:*Intel i5-8500 (3) @ 3.000GHz, Oracle Corporation VirtualBox VM*
[CPU Architecture / Device]

**Describe the bug**
[~] paul@Rhino $ gedit
Segmentation fault

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by axtloss** [comment]
This repo isn't about any issue experienced wirh gnome. We cannot help with gedit not working.

**Comment by paulyang81** [comment]
Bug had been fix by running "apt upgrade" on July-26-2024.
